<?php
/**
 * User: yongli
 * Date: 17/12/8
 * Time: 13:45
 * Email: yong.li@szypwl.com
 * Copyright: 深圳优品未来科技有限公司
 */
namespace App\Controllers\WifiAdmin;

use App\Controllers\BaseAdmin;
use WifiAdmin\NewsModel;

/**
 * 新闻管理动作控制器
 * Class NewsAction
 *
 * @package App\Controllers\WifiAdmin
 */
class News extends BaseAdmin
{
    /**
     * 构造方法
     */
    public function initialization()
    {
        parent::initialization(); // TODO: Change the autogenerated stub
        $this->doLoadID(700);
    }

    //
    public function index()
    {
        $build  = NewsModel::select(['id', 'title', 'info', 'mode', 'add_time']);
        $num    = $build->count();
        $result = $build->orderBy('add_time desc')->skip(($this->page - 1) * $this->perPage)->take($this->perPage)->get()->toArray();
        // 获得分页配置
        $config = set_page_config($num, $this->url, 3, $this->perPage);
        // 实例化分页类
        $pagination = \Config\Services::pagination();
        // 初始化分页配置
        $pagination->initialize($config);
        $page = $pagination->create_links();
        $this->assign('page', $page);
        $this->assign('lists', $result);
        $this->display();

    }

    /**
     * 添加新闻
     */
    public function add()
    {
        $post = $this->request->getPost();
        if ($post) {
            $post['add_time']    = time();
            $post['create_time'] = time();
            $post['update_time'] = time();
            $post['create_by']   = $this->uid;
            $post['update_by']   = $this->uid;
            $status              = NewsModel::insertGetId($post);
            $status ? call_back(0) : call_back(2, '', '操作失败!');
        } else {
            $this->display();
        }
    }

    /**
     * @return mixed
     */
    public function edit()
    {
        $post = $this->request->getPost();
        if ($post) {
            $post['update_time'] = time();
            $news                = NewsModel::select('id')->whereId($post['id'])->get()->toArray();
            $news                = $news ? $news[0] : [];
            !$news ? call_back(2, '', '当前记录不存在!') : '';
            $status = NewsModel::whereId($post['id'])->update($post);
            $status ? call_back(0) : call_back(2, '', '操作失败!');
        } else {
            $id   = $this->request->getGet('id');
            $id   = $id ? intval($id) : 0;
            $news = NewsModel::select('*')->whereId($id)->get()->toArray();
            $news = $news ? $news[0] : [];
            $this->assign('info', $news);
            $this->display();
        }

    }

    /**
     * 删除
     */
    public function del()
    {
        $id   = $this->request->getGet('id');
        $id   = $id ? intval($id) : 0;
        $news = NewsModel::select('id')->whereId($id)->get()->toArray();
        $news = $news ? $news[0] : [];
        if (!$news) {
            call_back(2, '', '没有此系统消息');
        }
        $status = NewsModel::whereId($id)->update(['is_delete' => 1]);
        $status ? call_back(0) : call_back(2, '', '操作失败!');
    }

}