<?php
/**
 * User: yongli
 * Date: 17/12/8
 * Time: 13:46
 * Email: yong.li@szypwl.com
 * Copyright: 深圳优品未来科技有限公司
 */
namespace App\Controllers\WifiAdmin;

use App\Controllers\BaseAdmin;
use WifiAdmin\NoticeModel;

/**
 * 信息管理
 * Class NoticeAction
 *
 * @package App\Controllers\WifiAdmin
 */
class Notice extends BaseAdmin
{
    /**
     * 构造函数
     */
    public function initialization()
    {
        parent::initialization(); // TODO: Change the autogenerated stub
        $this->doLoadID(700);
    }

    /**
     * [index 系统消息]
     * @return [type] [description]
     */
    public function index()
    {
        $build  = NoticeModel::select(['id', 'title', 'info', 'add_time']);
        $num    = $build->count();
        $result = $build->orderBy('id desc')->skip(($this->page - 1) * $this->perPage)->take($this->perPage)->get()->toArray();
        // 获得分页配置
        $config = set_page_config($num, $this->url, 3, $this->perPage);
        // 实例化分页类
        $pagination = \Config\Services::pagination();
        // 初始化分页配置
        $pagination->initialize($config);
        $page = $pagination->create_links();
        // 分配页码
        $this->assign('page', $page);
        // 分配数据
        $this->assign('lists', $result);
        $this->display();

    }

    /**
     * [add 添加系统消息]
     */
    public function add()
    {
        $post = $this->request->getPost();
        // 判断是否有POST数据提交
        if ($post) {
            // 设置添加时间、更新时间
            $post['add_time']    = time();
            $post['create_time'] = time();
            $post['update_time'] = time();
            $post['create_by']   = $this->uid;
            $post['update_by']   = $this->uid;
            $status              = NoticeModel::inserGetId($post);
            $status ? call_back(0) : call_back(2, '', '操作失败!');
        } else {
            $this->display();
        }
    }

    /**
     * 编辑系统信息
     *
     * @return mixed
     */
    public function edit()
    {
        $post = $this->request->getPost();
        $id   = $this->request->getPost('id') ?? $this->request->getGet('id');
        $info = NoticeModel::select('*')->whereId($id)->get()->toArray();
        $info = $info ? $info[0] : [];
        // 判读是否有POST数据提交
        if ($post) {
            // 设置更新时间
            $post['update_time'] = time();
            if (!$info) {
                //无此用户信息
                call_back(2, '', '没有此系统消息!');
            }
            $post['update_time'] = time();
            $post['update_by']   = $this->uid;
            $status              = NoticeModel::whereId($post['id'])->update($post);
            $status ? call_back(0) : call_back(2, '', '操作失败!');

        } else {
            // 分配数据
            $this->assign('info', $info);
            $this->display();
        }

    }

    /**
     * 删除系统信息
     *
     * @param $id
     */
    public function del($id)
    {
        $where['id'] = $id;
        $info        = NoticeModel::select('id')->whereId($id)->get()->toArray();
        $info        = $info ? $info[0] : [];
        if (!$info) {
            call_back(2, '', '没有此系统消息!');
        }
        $status = NoticeModel::whereId($id)->update(['is_delete' => 1]);
        $status ? call_back(0) : call_back(2, '', '操作失败!');
    }

}