<?php
/**
 * User: yongli
 * Date: 17/12/8
 * Time: 13:49
 * Email: yong.li@szypwl.com
 * Copyright: 深圳优品未来科技有限公司
 */
namespace App\Controllers\WifiAdmin;

use Agent\PushAdvModel;
use WifiAdmin\AdminPushSet;
use App\Controllers\BaseAdmin;
use Illuminate\Database\Capsule\Manager as DB;

/**
 * 广告推送
 * Class PushAdv
 *
 * @package App\Controllers\WifiAdmin
 */
class PushAdv extends BaseAdmin
{
    /**
     * 构造函数
     */
    public function initialization()
    {
        parent::initialization(); // TODO: Change the autogenerated stub
        $this->doLoadID(800);
    }

    /**
     * 推送设置
     */
    public function set()
    {
        $post = $this->request->getPost();
        // 获得推送设置信息
        $info = AdminPushSet::select('*')->get()->toArray();
        $info = $info ? $info[0] : [];
        // 判断是否有POST数据提交
        if ($post) {
            // 广告显示时间
            $wt = $post['wait_seconds'];
            if (!is_number($wt)) {
                call_back(2, '', '广告展示时间以秒为单位,请输入展示的时间!');
            }
            if ($wt < 3) {
                call_back(2, '', '最低展示时间不能小于3秒!');
            }
            // 有，就是更新
            if ($info) {
                $post['update_time'] = time();
                $post['update_by']   = $this->uid;
                //update
                $status = AdminPushSet::whereId($info['id'])->update($post);
            } else {
                $post['create_time'] = time();
                $post['update_time'] = time();
                $post['create_by']   = $this->uid;
                $post['update_by']   = $this->uid;
                // 没有，就是添加
                $status = AdminPushSet::insertGetId($post);
            }
            $status ? call_back(0) : call_back(2, '', '操作失败!');
        } else {
            // 分配数据
            $this->assign('info', $info);
            $this->display();
        }
    }

    /**
     * [index 推送广告管理]
     * @return [type] [description]
     */
    public function index()
    {
        $build  = PushAdvModel::select([
            'id',
            'title',
            'mode',
            'pic',
            'info',
            'sort',
            'show_count',
            'aid',
            'state',
            'start_time',
            'end_time'
        ])->with([
            'getAgent' => function ($query) {
                $query->select(['id', 'name']);
            }
        ]);
        $num    = $build->count();
        $result = $build->orderBy('id desc')->skip(($this->page - 1) * $this->perPage)->take($this->perPage)->get()->toArray();
        // 获得分页配置
        $config = set_page_config($num, $this->url, 3, $this->perPage);
        // 实例化分页类
        $pagination = \Config\Services::pagination();
        // 初始化分页配置
        $pagination->initialize($config);
        $page = $pagination->create_links();
        foreach ($result as &$rs) {
            $rs['pic'] = $this->downloadUrl($rs['pic']);
        }
        // 分配页码
        $this->assign('page', $page);
        // 分配广告数据
        $this->assign('lists', $result);
        $this->display();
    }

    /**
     * [add 添加推送广告]
     */
    public function add()
    {
        $post = $this->request->getPost();
        // 判断是否有POST数据提交
        if ($post) {
            // 设置添加时间
            $post['add_time'] = time();
            // 检测投送广告投放时间段
            if ($post['start_date'] == '' || $post['end_date'] == '') {
                call_back(2, '', '请选择广告投放时间段');
            }
            // 分别给$ret，$err赋值
            $post['pic']         = $this->uploadFile($this->uid, $_FILES['img']['name'], $_FILES['img']['tmp_name']);
            $post['start_date']  = strtotime($post['start_date']);
            $post['end_date']    = strtotime($post['end_date']);
            $post['create_time'] = time();
            $post['update_time'] = time();
            $post['create_by']   = $this->uid;
            $post['update_by']   = $this->uid;
            $status              = PushAdvModel::insertGetId($post);
            $status ? call_back(0) : call_back(2, '', '操作失败!');
            //                    $this->success('添加广告成功', U('pushadv/index', '', true, true, true));
        } else {
            // 没有POST数据提交就显示添加模板
            $this->display();
        }
    }

    /**
     * 编辑推送广告
     */
    public function edit()
    {
        $post = $this->request->getPost();
        // 查找条件
        $id = $this->request->getGet('id');
        // 获得当前要编辑的广告信息
        $result = PushAdvModel::whereId($id)->get()->toArray();
        $result = $result ? $result[0] : [];
        // 判断是否有POST数据提交
        if ($post) {
            if (!$result) {
                call_back(2, '', '当前广告信息不存在!');
            }
            // 检测是否设置广告投放时间段
            if ($post['start_date'] == '' || $post['end_date'] == '') {
                call_back(2, '', '请选择广告投放时间段');
            }
            // 检测图片是否上传成功
            if (!is_null($_FILES['img']['name']) && $_FILES['img']['name'] != '') {
                $post['pic'] = $this->uploadFile($this->uid, $_FILES['img']['name'], $_FILES['img']['tmp_name']);
            } else {
                $post['pic'] = $result['pic'];
            }
            // 转换时间显示方式
            $post['startdate']   = strtotime($post ['start_date']);
            $post['end_date']    = strtotime($post ['end_date']);
            $post['update_time'] = time();
            $post['update_by']   = $this->uid;
            $status              = PushAdvModel::whereId($post['id'])->update($post);
            $status ? call_back(0) : call_back(2, '', '操作失败!');

        } else {
            $result['pic'] = $this->downloadUrl($result ['pic']);
            // 分配当前广告信息
            $this->assign('info', $result);
            $this->display();
        }
    }

    /**
     * 删除广告
     *
     * @param $id
     */
    public function del($id)
    {
        // 获得当前广告的图片信息
        $result = PushAdvModel::select(['id', 'pic'])->whereId($id)->get()->toArray();
        $result = $result ? $result[0] : [];
        if (!$result) {
            call_back(2, '', '该广告不存在!');
        }
        // 删除当前广告
        $status = PushAdvModel::whereId($id)->update(['is_delete' => 1]);
        $status ? call_back(0) : call_back(2, '', '操作失败!');
    }

    /**
     * 广告推送统计
     */
    public function rpt()
    {
        // 获得查询的方式
        $way = $this->request->getGet('mode');
        if ($way) {
            // 获得相应查询下的结果
            $data = $this->_getAdRpt($way);
            call_back(0, $data);
        }
        $this->display();
    }

    /**
     * 广告报表
     *
     * @param $way
     */
    private function _getAdRpt($way)
    {
        // 获得当前商户的广告id
        $where = ' where shop_id=' . $this->uid;
        switch (strtolower($way)) {
            case 'today' :
                $sql = 'select t,CONCAT(CURDATE()," ",t,"点") as show_date, COALESCE(show_up,0)  as showup, COALESCE(hit,0)  as hit,COALESCE(hit/show_up*100,0) as rt from wifi_hours a left JOIN ';
                $sql .= '(select thour, sum(show_up)as show_up,sum(hit) as hit,  ';
                $sql .= 'sum(case when mode=99 then show_up else 0 end) as pshowup, ';
                $sql .= 'sum(case when mode=50 then show_up else 0 end) as ashowup, ';
                $sql .= 'sum(case when mode=99 then hit else 0 end) as phit, ';
                $sql .= 'sum(case when mode=99 then show_up else 0 end) as ahit from ';
                $sql .= '(select  FROM_UNIXTIME(add_time, "%H") as thour,showup ,hit,mode from wifi_ad_count ';
                $sql .= 'where add_date="' . date('Y-m-d', time()) . '" and (mode=99 or mode=50) ';
                $sql .= ' )a group by thour ) c ';
                $sql .= '  on a.t=c.thour ';
                break;
            case 'yesterday' :
                $sql = 'select t,CONCAT(CURDATE()," ",t,"点") as show_date, COALESCE(show_up,0)  as show_up, COALESCE(hit,0)  as hit,COALESCE(hit/show_up*100,0) as rt from wifi_hours a left JOIN ';
                $sql .= '(select thour, sum(show_up)as show_up,sum(hit) as hit,  ';
                $sql .= 'sum(case when mode=99 then show_up else 0 end) as pshowup, ';
                $sql .= 'sum(case when mode=50 then show_up else 0 end) as ashowup, ';
                $sql .= 'sum(case when mode=99 then hit else 0 end) as phit, ';
                $sql .= 'sum(case when mode=99 then show_up else 0 end) as ahit from ';
                $sql .= '(select  FROM_UNIXTIME(add_time,"%H") as thour,showup ,hit from wifi_adcount ';
                $sql .= 'where add_date=DATE_ADD(CURDATE() ,INTERVAL -1 DAY) and (mode=99 or mode=50) ';
                $sql .= ' )a group by thour ) c ';
                $sql .= ' on a.t=c.thour ';
                break;
            case 'week' :
                $sql = 'select td as show_date,right(td,5) as td,datediff(td,CURDATE()) as t, COALESCE(show_up,0)  as show_up, COALESCE(hit,0)  as hit ,COALESCE(hit/show_up*100,0) as rt from ';
                $sql .= '( select CURDATE() as td ';
                for ($i = 1; $i < 7; $i++) {
                    $sql .= '  UNION all select DATE_ADD(CURDATE() ,INTERVAL -' . $i . ' DAY) ';
                }
                $sql .= 'ORDER BY td ) a left join ';
                $sql .= '( select add_date,sum(show_up) as show_up ,sum(hit) as hit from wifi_ad_count ';
                $sql .= 'where   add_date between DATE_ADD(CURDATE() ,INTERVAL -6 DAY) and CURDATE() and (mode=99 or mode=50) GROUP BY  add_date ';
                $sql .= ') b on a.td=b.add_date ';
                break;
            case 'month' :
                $sql = 'select tname as show_date,tname as t, COALESCE(show_up,0)  as show_up, COALESCE(hit,0)  as hit,COALESCE(hit/show_up*100,0) as rt from wifi_day  a left JOIN ';
                $sql .= '( select right(add_date,2) as td ,sum(show_up) as show_up ,sum(hit) as hit  from wifi_ad_count  ';
                $sql .= 'where   add_date >= "' . date('Y-m-01',
                        time()) . '" and (mode=99 or mode=50) GROUP BY  add_date ';
                $sql .= ') b on a.tname=b.td ';
                $sql .= 'where a.id between 1 and  ' . date('t');
                break;
            case "query" :
                $start_date = $this->request->getGet('start_date');
                $end_date   = $this->request->getGet('end_date');
                //                import("ORG.Util.Date");
                $dt      = new Date ($start_date);
                $leftDay = $dt->dateDiff($end_date, 'd');
                $sql     = 'select td as showdate,right(td,5) as td,datediff(td,CURDATE()) as t,COALESCE(show_up,0)  as show_up, COALESCE(hit,0)  as hit,COALESCE(hit/show_up*100,0) as rt from ';
                $sql .= '( select "' . $start_date . '" as td ';
                for ($i = 0; $i <= $leftDay; $i++) {
                    $sql .= '  UNION all select DATE_ADD("' . $start_date . '"" ,INTERVAL ' . $i . ' DAY) ';
                }
                $sql .= ') a left join ';
                $sql .= '( select add_date,sum(show_up) as show_up ,sum(hit) as hit  from wifi_ad_count ';
                $sql .= ' where  add_date between "' . $start_date . '" and "' . $end_date . '"  and (mode=99 or mode=50) GROUP BY  add_date ';
                $sql .= ') b on a.td=b.add_date ';
                break;
        }
        $result = DB::select($sql);

        return $result;
    }

}